# -*- coding: utf-8 -*-
"""AI_Data_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xY6jsSnRio9XB5YgtjMZvdR3m-G1JlhS
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import zipfile
import io
import os

# Get the name of the uploaded zip file
zip_file_name = next(iter(uploaded)) # Assuming 'uploaded' dictionary from previous cell

# Unzip the file and read the content
with zipfile.ZipFile(io.BytesIO(uploaded[zip_file_name]), 'r') as z:
    # Get the name of the CSV file inside the zip archive
    # Assuming there's only one CSV file or we want the first one ending with .csv
    csv_files_in_zip = [name for name in z.namelist() if name.endswith('.csv')]
    if not csv_files_in_zip:
        raise ValueError("No CSV file found inside the zip archive.")

    csv_file_name_to_read = csv_files_in_zip[0]

    z.extractall() # Extracts all files to the current directory

df = pd.read_csv(csv_file_name_to_read, low_memory=False)
df.head()

df.shape
df.info()
df.describe()

df = df.dropna()           # remove missing values
df = df.drop_duplicates()  # remove duplicates

import pandas as pd

# Reload the original CSV file to get the columns before any data cleaning operations.
# The csv_file_name_to_read variable holds the name of the extracted csv file.
original_df = pd.read_csv(csv_file_name_to_read, low_memory=False)
print("Columns in the original DataFrame:")
for col in original_df.columns:
    print(col)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(original_df['hhcode'], original_df['age1'])
plt.xlabel('Household Code (hhcode)')
plt.ylabel('Age of Person 1 (age1)')
plt.title('Scatter Plot of hhcode vs age1')
plt.grid(True)
plt.show()

original_df['gender1'].value_counts().plot(kind='bar')

import seaborn as sns
import matplotlib.pyplot as plt

# Using original_df because df is empty, and using 'age1' as a valid column example
sns.boxplot(x=original_df['age1'])
plt.title('Boxplot of Age 1')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Select a small subset of numeric columns for a readable heatmap
subset_cols = ['age1', 'age2', 'educ1', 'educ2', 'hhcode']
correlation_matrix = original_df[subset_cols].corr(numeric_only=True)

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap (Subset of Columns)')
plt.show()